apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: external-dns
  namespace: kube-system
  repo: https://kubernetes-sigs.github.io/external-dns/
  version: "'1.16.1'"
  releaseName: external-dns
  includeCRDs: true
  valuesFile: values.yaml
